name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '1.8'
          distribution: 'openjdk'

      - name: GLogger package
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
