name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package

      - name: GLogger package
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
