name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw clean install
      - name: GLogger package
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PATH_TOKEN }}
